# -*- coding: utf-8 -*-
"""HTML-Styler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1T8Xkl9-7LsEJCWJS1dAk1nJtU-EcOO
"""

!pip install transformers accelerate torch gradio huggingface_hub

import torch

print("PyTorch Version:", torch.__version__)
print("GPU Available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16
)

prompt = "Explain Artificial Intelligence simply"

inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

outputs = model.generate(**inputs, max_new_tokens=150)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

def generate_text(prompt):

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=200,
        temperature=0.7,
        top_p=0.9,
        do_sample=True
    )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

!pip install gradio

import gradio as gr

def echo(text):
    return text

demo = gr.Interface(fn=echo, inputs="text", outputs="text")

demo.launch()

class ColorPaletteGenerator:

    def __init__(self):

        self.palettes = {

            "modern":["#3498db","#2ecc71","#2c3e50","#ecf0f1"],
            "dark":["#121212","#1f1f1f","#333333","#ffffff"],
            "sunset":["#ff6b6b","#feca57","#ff9ff3","#48dbfb"],
            "ocean":["#00a8ff","#0097e6","#273c75","#f5f6fa"],
            "nature":["#27ae60","#2ecc71","#145a32","#d5f5e3"],
            "royal":["#6a1b9a","#8e44ad","#d2b4de","#f5eef8"],
            "minimal":["#ffffff","#f1f2f6","#2f3542","#57606f"],
            "vibrant":["#ff4757","#1e90ff","#ffa502","#2ed573"]
        }

    def get_palette(self,name):
        return self.palettes.get(name,self.palettes["modern"])

class HTMLPageBuilder:

    def generate_meta(self,title,desc):

        return f"""
        <title>{title}</title>
        <meta name="description" content="{desc}">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        """

    def build_page(self,title,desc,content):

        meta=self.generate_meta(title,desc)

        html=f"""
        <!DOCTYPE html>
        <html>
        <head>
        {meta}
        </head>

        <body>

        {content}

        </body>
        </html>
        """

        return html

class CSSGenerator:

    def generate_css(self,palette):

        primary = palette[0]
        secondary = palette[1]
        dark = palette[2]
        light = palette[3]

        css = f"""

        body {{
            font-family: Arial, sans-serif;
            margin:0;
            background:{light};
            color:{dark};
        }}

        .hero {{
            text-align:center;
            padding:80px;
            background:{primary};
            color:white;
        }}

        .features {{
            display:grid;
            grid-template-columns:repeat(auto-fit,minmax(200px,1fr));
            gap:20px;
            padding:40px;
        }}

        .feature {{
            background:{secondary};
            padding:20px;
            border-radius:10px;
            text-align:center;
            color:white;
            font-weight:bold;
        }}

        section {{
            padding:40px;
        }}

        h2 {{
            margin-bottom:20px;
        }}

        input, textarea {{
            width:100%;
            padding:12px;
            margin:10px 0;
            border-radius:6px;
            border:1px solid #ccc;
            background:white;
            color:black;
            font-size:16px;
        }}

        textarea {{
            height:120px;
        }}

        button {{
            padding:12px 25px;
            background:{primary};
            border:none;
            color:white;
            border-radius:6px;
            cursor:pointer;
            font-size:16px;
        }}

        button:hover {{
            background:{secondary};
        }}

        @media(max-width:768px) {{
            .hero {{
                padding:40px;
            }}
        }}

        """

        return css

def hero_section(title,subtitle):

    return f"""
    <section class="hero">
    <h1>{title}</h1>
    <p>{subtitle}</p>
    </section>
    """

def features_section(features):

    items=""

    for f in features:
        items+=f"<div class='feature'>{f}</div>"

    return f"""
    <section class="features">
    {items}
    </section>
    """

def contact_section():

    return """
    <section>
    <h2>Contact Us</h2>

    <input placeholder="Name">
    <input placeholder="Email">
    <textarea placeholder="Message"></textarea>

    <button>Send</button>

    </section>
    """

palette_gen=ColorPaletteGenerator()
css_gen=CSSGenerator()
builder=HTMLPageBuilder()

import gradio as gr

def generate_site(title,subtitle):

    hero=hero_section(title,subtitle)

    features=features_section([
        "Fast Generation",
        "Responsive Design",
        "AI Powered"
    ])

    contact=contact_section()

    content=hero+features+contact

    palette=palette_gen.get_palette("modern")

    css=css_gen.generate_css(palette)

    html=builder.build_page(title,"AI Generated Website",content)

    final="<style>"+css+"</style>"+html

    return final


interface=gr.Interface(
    fn=generate_site,
    inputs=["text","text"],
    outputs=gr.HTML(),
    title="AI Website Generator"
)

interface.launch()

generate_site(
"My Startup Website",
"Build your future with AI"
)

interface.launch(share=True)

